name: CD

on:
  push:
    branches:
      - "master"

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          version: '1.25.0-8.3.pre'
      - name: test
        run: flutter --version
      - name: Install Flutter dependencies
        run: flutter pub get
#     - name: Format files
#       run: flutter format --set-exit-if-changed .
#     - name: Analyze files
#       run: flutter analyze .
#     - name: Run the tests
#       run: flutter test

  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.0-13.0.pre.179'
          channel: 'master'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Fill up .env
        run: echo "$ENV" > .env
        env:
          ENV: ${{ secrets.ENV }}
      - name: Build flutter bundle for android
        run: flutter build appbundle
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: maierj/fastlane-action@v2.0.0
        with:
          lane: closed_beta
          subdirectory: android
  deploy_ios:
    runs-on: macOS-latest
    needs: [build_android]
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.0-13.0.pre.179'
          channel: 'master'
      - run: flutter pub get
      - name: Fill up .env
        run: echo "$ENV" > .env
        env:
          ENV: ${{ secrets.ENV }}
      - run: flutter build ios --release --no-codesign
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: maierj/fastlane-action@v2.0.0
        with:
          lane: sync_version
          subdirectory: ios
      - uses: maierj/fastlane-action@v2.0.0
        with:
          lane: closed_beta
          subdirectory: ios
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_APP_SIGNAL_IDENTIFIER: '${{ secrets.DEVELOPER_APP_SIGNAL_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          PROVISIONING_SIGNAL_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_SIGNAL_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
